#!/usr/bin/env python3
from __future__ import annotations

import argparse
import math
from datetime import datetime
from pathlib import Path


from huggingface_hub import hf_hub_download

from irodori_tts.long_generation import LongExportOptions, export_long_audio, split_long_text
from irodori_tts.inference_runtime import (
    InferenceRuntime,
    RuntimeKey,
    SamplingRequest,
    default_runtime_device,
    resolve_cfg_scales,
    save_wav,
)


def _parse_optional_float(value: str) -> float | None:
    raw = str(value).strip().lower()
    if raw in {"none", "null", "off", "disable", "disabled"}:
        return None
    try:
        out = float(raw)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            "Expected float or one of [none, null, off, disable, disabled]."
        ) from exc
    if not math.isfinite(out):
        raise argparse.ArgumentTypeError(f"Expected finite float for value={value!r}.")
    return out


def _print_timings(timings: list[tuple[str, float]], total_to_decode: float) -> None:
    print("[timing] ---- post-model-load to decode ----")
    for name, sec in timings:
        print(f"[timing] {name}: {sec * 1000.0:.1f} ms")
    print(f"[timing] total_to_decode: {total_to_decode:.3f} s")


def _resolve_checkpoint_path(args: argparse.Namespace) -> str:
    if args.checkpoint is not None:
        checkpoint_path = Path(str(args.checkpoint)).expanduser()
        if not checkpoint_path.is_file():
            raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")
        print(f"[checkpoint] using local file: {checkpoint_path}", flush=True)
        return str(checkpoint_path)

    repo_id = str(args.hf_checkpoint).strip()
    if repo_id == "":
        raise ValueError("hf_checkpoint must be non-empty.")

    checkpoint_path = hf_hub_download(
        repo_id=repo_id,
        filename="model.safetensors",
    )
    print(
        f"[checkpoint] downloaded model.safetensors from hf://{repo_id} -> {checkpoint_path}",
        flush=True,
    )
    return str(checkpoint_path)


def main() -> None:
    parser = argparse.ArgumentParser(description="Inference for Irodori-TTS.")
    checkpoint_group = parser.add_mutually_exclusive_group(required=True)
    checkpoint_group.add_argument(
        "--checkpoint",
        default=None,
        help="Local model checkpoint path (.pt or .safetensors).",
    )
    checkpoint_group.add_argument(
        "--hf-checkpoint",
        default=None,
        help=(
            "Hugging Face model repo id to download model.safetensors from "
            "(e.g. your-org/your-model)."
        ),
    )
    parser.add_argument(
        "--lora-adapter",
        default=None,
        help=(
            "Optional PEFT LoRA adapter directory to load dynamically for this inference run. "
            "The adapter is applied at runtime and is not merged into the base checkpoint."
        ),
    )
    text_group = parser.add_mutually_exclusive_group(required=True)
    text_group.add_argument("--text", default=None, help="Text to synthesize.")
    text_group.add_argument("--text-file", default=None, help="UTF-8 text file to synthesize.")
    parser.add_argument(
        "--caption",
        default=None,
        help="Optional caption/style-control text for caption-enabled voice-design checkpoints.",
    )
    parser.add_argument("--output-wav", default="output.wav")
    parser.add_argument(
        "--long",
        action="store_true",
        help="Enable long-form chunked generation. Text is split into chunks and then joined.",
    )
    parser.add_argument("--output-dir", default="outputs_long", help="Output directory for --long.")
    parser.add_argument("--output-stem", default=None, help="Output filename stem for --long.")
    parser.add_argument(
        "--output-format",
        choices=["wav", "mp3"],
        default="wav",
        help="Final output format for --long.",
    )
    parser.add_argument(
        "--chunk-max-chars",
        type=int,
        default=80,
        help="Maximum characters per chunk for --long. Japanese punctuation/newlines are preferred split points.",
    )
    parser.add_argument(
        "--pause-ms",
        type=int,
        default=250,
        help="Silence inserted between chunks for --long.",
    )
    parser.add_argument(
        "--keep-final-wav-when-mp3",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="For --long --output-format mp3, also keep the joined WAV.",
    )
    parser.add_argument(
        "--keep-chunk-wavs",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Keep per-chunk WAV files generated by --long.",
    )
    parser.add_argument(
        "--save-json",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Save JSON sidecar and append JSONL generation log for --long.",
    )
    parser.add_argument(
        "--write-mp3-tag",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Write generation parameters to MP3 COMMENT/TXXX tags for --long MP3 output.",
    )
    parser.add_argument(
        "--jsonl-path",
        default=None,
        help="Optional JSONL log path for --long. Defaults to <output-dir>/generation_log.jsonl.",
    )
    parser.add_argument(
        "--ffmpeg-exe",
        default=None,
        help="Optional ffmpeg executable path used by pydub for --long MP3 export.",
    )
    parser.add_argument(
        "--model-device",
        default=default_runtime_device(),
        help="Model inference device (e.g. cuda, mps, cpu).",
    )
    parser.add_argument(
        "--model-precision",
        choices=["fp32", "bf16"],
        default="fp32",
        help="Model precision for weights/compute.",
    )
    parser.add_argument(
        "--codec-device",
        default=default_runtime_device(),
        help="Codec device for reference encode/decode (e.g. cuda, mps, cpu).",
    )
    parser.add_argument(
        "--codec-precision",
        choices=["fp32", "bf16"],
        default="fp32",
        help="Codec precision for weights/compute.",
    )
    parser.add_argument(
        "--codec-deterministic-encode",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Use deterministic DACVAE encode path (default: enabled).",
    )
    parser.add_argument(
        "--codec-deterministic-decode",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Use deterministic DACVAE decode path (default: enabled).",
    )
    parser.add_argument(
        "--max-ref-seconds",
        type=float,
        default=30.0,
        help="Maximum reference duration in seconds. Set <=0 to disable the cap.",
    )
    parser.add_argument(
        "--ref-normalize-db",
        type=_parse_optional_float,
        default=-16.0,
        help=(
            "Target loudness (dB/LUFS-like) for reference audio before DACVAE encode "
            "(e.g. -16.0). Set to 'none' to disable. Default: -16."
        ),
    )
    parser.add_argument(
        "--ref-ensure-max",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Scale reference audio down only when peak exceeds 1.0 after optional loudness "
            "normalization. Effective only when --ref-normalize-db is none/null/off "
            "(default: enabled)."
        ),
    )
    parser.add_argument("--codec-repo", default="Aratako/Semantic-DACVAE-Japanese-32dim")
    parser.add_argument(
        "--max-text-len",
        type=int,
        default=None,
        help=(
            "Maximum token length for text conditioning. "
            "Defaults to checkpoint metadata max_text_len when available, else 256."
        ),
    )
    parser.add_argument(
        "--max-caption-len",
        type=int,
        default=None,
        help=(
            "Maximum token length for caption conditioning. "
            "Defaults to checkpoint metadata max_caption_len when available, else max_text_len."
        ),
    )
    parser.add_argument("--num-steps", type=int, default=40)
    parser.add_argument(
        "--t-schedule-mode",
        choices=["linear", "sway"],
        default="linear",
        help="Timestep schedule for RF Euler sampling.",
    )
    parser.add_argument(
        "--sway-coeff",
        type=float,
        default=-1.0,
        help="Sway Sampling coefficient used when --t-schedule-mode=sway.",
    )
    parser.add_argument(
        "--seconds",
        type=float,
        default=None,
        help=(
            "Manual output duration in seconds. If omitted, duration-enabled checkpoints "
            "predict duration automatically; older checkpoints fall back to 30s."
        ),
    )
    parser.add_argument(
        "--duration-scale",
        type=float,
        default=1.0,
        help="Scale predicted duration when --seconds is omitted (>1 longer, <1 shorter).",
    )
    parser.add_argument(
        "--num-candidates",
        type=int,
        default=1,
        help="Number of candidates to generate in a single batched sampling pass.",
    )
    parser.add_argument(
        "--decode-mode",
        choices=["sequential", "batch"],
        default="sequential",
        help=(
            "Codec decode mode. "
            "'sequential': decode each candidate one-by-one (lower VRAM), "
            "'batch': decode all candidates at once (faster, higher VRAM)."
        ),
    )
    parser.add_argument(
        "--compile-model",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Enable torch.compile for core inference methods (default: disabled).",
    )
    parser.add_argument(
        "--compile-dynamic",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Use dynamic=True for torch.compile (default: disabled).",
    )
    parser.add_argument("--cfg-scale-text", type=float, default=3.0)
    parser.add_argument("--cfg-scale-caption", type=float, default=3.0)
    parser.add_argument("--cfg-scale-speaker", type=float, default=5.0)
    parser.add_argument(
        "--cfg-guidance-mode",
        choices=["independent", "joint", "alternating"],
        default="independent",
        help=(
            "CFG formulation. "
            "'independent': each enabled condition uses its own uncond pass, "
            "'joint': drop all enabled conditions together (2x NFE), "
            "'alternating': alternate enabled condition unconds each step."
        ),
    )
    parser.add_argument(
        "--cfg-scale",
        type=float,
        default=None,
        help="Deprecated. If set, overrides --cfg-scale-text/--cfg-scale-caption/--cfg-scale-speaker.",
    )
    parser.add_argument("--cfg-min-t", type=float, default=0.5)
    parser.add_argument("--cfg-max-t", type=float, default=1.0)
    parser.add_argument(
        "--truncation-factor",
        type=float,
        default=None,
        help=(
            "Scale initial Gaussian noise before Euler sampling "
            "(e.g., 0.8 flat / 0.9 sharp). Default: disabled."
        ),
    )
    parser.add_argument(
        "--rescale-k",
        type=float,
        default=None,
        help=(
            "Temporal score rescaling k (Xu et al., 2025). "
            "Set together with --rescale-sigma. Default: disabled."
        ),
    )
    parser.add_argument(
        "--rescale-sigma",
        type=float,
        default=None,
        help=(
            "Temporal score rescaling sigma (Xu et al., 2025). "
            "Set together with --rescale-k. Default: disabled."
        ),
    )
    parser.add_argument(
        "--context-kv-cache",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Precompute per-layer text/speaker context K/V projections for faster sampling "
            "(default: enabled)."
        ),
    )
    parser.add_argument(
        "--speaker-kv-scale",
        type=float,
        default=None,
        help=(
            "Force-speaker mode: scale speaker K/V projections by this factor (>1 strengthens speaker identity). "
            "Default: disabled."
        ),
    )
    parser.add_argument(
        "--speaker-kv-min-t",
        type=float,
        default=0.9,
        help=(
            "Disable speaker KV scaling after crossing this timestep threshold "
            "(applies while t >= value). Default: 0.9."
        ),
    )
    parser.add_argument(
        "--speaker-kv-max-layers",
        type=int,
        default=None,
        help="Apply speaker KV scaling only to first N diffusion layers (default: all layers).",
    )
    parser.add_argument(
        "--speaker-uncond-mode",
        choices=["mask", "noise"],
        default="mask",
        help=(
            "Unconditional speaker embedding formulation for speaker-conditioned checkpoints. "
            "'mask': zero out the embedding (default, lower VRAM). "
            "'noise': replace with Gaussian noise of the same stddev as the reference embedding."
        ),
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Sampling seed. If omitted, a random seed is generated per request.",
    )
    parser.add_argument(
        "--trim-tail",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Trim trailing near-zero latent region with Echo-style flattening heuristic "
            "(default: enabled)."
        ),
    )
    parser.add_argument("--tail-window-size", type=int, default=20)
    parser.add_argument("--tail-std-threshold", type=float, default=0.05)
    parser.add_argument("--tail-mean-threshold", type=float, default=0.1)
    parser.add_argument(
        "--show-timings",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Print per-stage timings from post-model-load through latent decode (default: enabled)."
        ),
    )
    ref_group = parser.add_mutually_exclusive_group(required=False)
    ref_group.add_argument(
        "--ref-wav",
        default=None,
        help="Reference waveform path for speaker conditioning.",
    )
    ref_group.add_argument(
        "--ref-latent",
        default=None,
        help="Reference latent (.pt) path for speaker conditioning.",
    )
    ref_group.add_argument(
        "--ref-embed",
        default=None,
        help=("Speaker Inversion embedding (.speaker.safetensors) path for speaker conditioning."),
    )
    ref_group.add_argument(
        "--no-ref",
        action="store_true",
        help=(
            "Run without speaker reference conditioning. Valid for text-only or "
            "text+caption-only inference even when the checkpoint supports speaker conditioning."
        ),
    )
    args = parser.parse_args()

    if args.text_file is not None:
        text_value = Path(str(args.text_file)).read_text(encoding="utf-8").strip()
    else:
        text_value = str(args.text).strip()
    if text_value == "":
        parser.error("text is empty.")
    if bool(args.long) and int(args.num_candidates) != 1:
        parser.error("--long currently supports --num-candidates 1 only.")
    if bool(args.long) and int(args.chunk_max_chars) < 20:
        parser.error("--chunk-max-chars must be >= 20.")
    if bool(args.long) and int(args.pause_ms) < 0:
        parser.error("--pause-ms must be >= 0.")

    checkpoint_path = _resolve_checkpoint_path(args)

    runtime = InferenceRuntime.from_key(
        RuntimeKey(
            checkpoint=checkpoint_path,
            model_device=str(args.model_device),
            codec_repo=str(args.codec_repo),
            model_precision=str(args.model_precision),
            codec_device=str(args.codec_device),
            codec_precision=str(args.codec_precision),
            codec_deterministic_encode=bool(args.codec_deterministic_encode),
            codec_deterministic_decode=bool(args.codec_deterministic_decode),
            compile_model=bool(args.compile_model),
            compile_dynamic=bool(args.compile_dynamic),
        )
    )
    if runtime.model_cfg.use_speaker_condition_resolved and not (
        args.no_ref
        or args.ref_wav is not None
        or args.ref_latent is not None
        or args.ref_embed is not None
    ):
        parser.error(
            "speaker-conditioned checkpoints require one of --ref-wav, --ref-latent, "
            "--ref-embed, or --no-ref."
        )
    use_speaker_for_request = bool(
        runtime.model_cfg.use_speaker_condition_resolved and not args.no_ref
    )
    cfg_scale_text, cfg_scale_caption, cfg_scale_speaker, scale_messages = resolve_cfg_scales(
        cfg_guidance_mode=str(args.cfg_guidance_mode),
        cfg_scale_text=float(args.cfg_scale_text),
        cfg_scale_caption=float(args.cfg_scale_caption),
        cfg_scale_speaker=float(args.cfg_scale_speaker),
        cfg_scale=float(args.cfg_scale) if args.cfg_scale is not None else None,
        use_caption_condition=bool(
            runtime.model_cfg.use_caption_condition
            and args.caption is not None
            and str(args.caption).strip() != ""
        ),
        use_speaker_condition=use_speaker_for_request,
    )
    for msg in scale_messages:
        print(msg)

    def synthesize_text(chunk_text: str, seed: int | None) -> object:
        return runtime.synthesize(
            SamplingRequest(
                text=str(chunk_text),
                caption=None if args.caption is None else str(args.caption),
                ref_wav=args.ref_wav,
                ref_latent=args.ref_latent,
                ref_embed=args.ref_embed,
                no_ref=bool(args.no_ref),
                ref_normalize_db=args.ref_normalize_db,
                ref_ensure_max=bool(args.ref_ensure_max),
                num_candidates=1 if bool(args.long) else int(args.num_candidates),
                decode_mode=str(args.decode_mode),
                seconds=None if args.seconds is None else float(args.seconds),
                duration_scale=float(args.duration_scale),
                max_ref_seconds=float(args.max_ref_seconds)
                if args.max_ref_seconds is not None
                else None,
                max_text_len=None if args.max_text_len is None else int(args.max_text_len),
                max_caption_len=None if args.max_caption_len is None else int(args.max_caption_len),
                num_steps=int(args.num_steps),
                cfg_scale_text=cfg_scale_text,
                cfg_scale_caption=cfg_scale_caption,
                cfg_scale_speaker=cfg_scale_speaker,
                cfg_guidance_mode=str(args.cfg_guidance_mode),
                cfg_scale=None,
                cfg_min_t=float(args.cfg_min_t),
                cfg_max_t=float(args.cfg_max_t),
                truncation_factor=None
                if args.truncation_factor is None
                else float(args.truncation_factor),
                rescale_k=None if args.rescale_k is None else float(args.rescale_k),
                rescale_sigma=None if args.rescale_sigma is None else float(args.rescale_sigma),
                context_kv_cache=bool(args.context_kv_cache),
                speaker_kv_scale=None
                if args.speaker_kv_scale is None
                else float(args.speaker_kv_scale),
                speaker_kv_min_t=None
                if args.speaker_kv_scale is None
                else float(args.speaker_kv_min_t),
                speaker_kv_max_layers=None
                if args.speaker_kv_max_layers is None
                else int(args.speaker_kv_max_layers),
                speaker_uncond_mode=str(args.speaker_uncond_mode),
                seed=seed,
                t_schedule_mode=str(args.t_schedule_mode),
                sway_coeff=float(args.sway_coeff),
                trim_tail=bool(args.trim_tail),
                tail_window_size=int(args.tail_window_size),
                tail_std_threshold=float(args.tail_std_threshold),
                tail_mean_threshold=float(args.tail_mean_threshold),
                lora_adapter=None if args.lora_adapter is None else str(args.lora_adapter),
            ),
            log_fn=None,
        )

    if bool(args.long):
        chunks = split_long_text(text_value, max_chars=int(args.chunk_max_chars))
        output_dir = Path(str(args.output_dir))
        output_stem = args.output_stem or datetime.now().strftime("irodori_long_%Y%m%d_%H%M%S")
        chunk_dir = output_dir / "chunks" / output_stem
        chunk_dir.mkdir(parents=True, exist_ok=True)
        chunk_wavs: list[Path] = []
        chunk_logs: list[dict[str, object]] = []
        timing_logs: list[tuple[int, list[tuple[str, float]], float]] = []
        sample_rate = None

        print(f"[long] chunks: {len(chunks)}")
        for index, chunk_text in enumerate(chunks, start=1):
            chunk_seed = None if args.seed is None else int(args.seed) + index - 1
            print(f"[long] chunk {index}/{len(chunks)}: {chunk_text}")
            result = synthesize_text(chunk_text, chunk_seed)
            sample_rate = result.sample_rate
            chunk_wav = chunk_dir / f"{output_stem}_chunk_{index:03d}.wav"
            saved_chunk = save_wav(chunk_wav, result.audio, result.sample_rate)
            chunk_wavs.append(Path(saved_chunk))
            chunk_logs.append(
                {
                    "index": index,
                    "text": chunk_text,
                    "seed_requested": chunk_seed,
                    "seed_used": result.used_seed,
                    "wav": str(saved_chunk),
                    "messages": result.messages,
                    "total_to_decode": result.total_to_decode,
                }
            )
            timing_logs.append((index, result.stage_timings, result.total_to_decode))

        metadata = {
            "mode": "long_cli",
            "checkpoint": checkpoint_path,
            "codec_repo": str(args.codec_repo),
            "text": text_value,
            "text_file": str(args.text_file) if args.text_file is not None else None,
            "caption": None if args.caption is None else str(args.caption),
            "sample_rate": sample_rate,
            "chunk_max_chars": int(args.chunk_max_chars),
            "chunks": chunk_logs,
            "num_steps": int(args.num_steps),
            "seed_base": args.seed,
            "seconds": args.seconds,
            "duration_scale": float(args.duration_scale),
            "cfg_guidance_mode": str(args.cfg_guidance_mode),
            "cfg_scale_text": cfg_scale_text,
            "cfg_scale_caption": cfg_scale_caption,
            "cfg_scale_speaker": cfg_scale_speaker,
            "ref_wav": args.ref_wav,
            "ref_latent": args.ref_latent,
            "ref_embed": args.ref_embed,
            "no_ref": bool(args.no_ref),
        }
        final_audio, final_metadata = export_long_audio(
            chunk_wavs=chunk_wavs,
            options=LongExportOptions(
                output_dir=output_dir,
                output_stem=output_stem,
                output_format=str(args.output_format),
                pause_ms=int(args.pause_ms),
                keep_final_wav_when_mp3=bool(args.keep_final_wav_when_mp3),
                keep_chunk_wavs=bool(args.keep_chunk_wavs),
                save_json=bool(args.save_json),
                write_mp3_tag=bool(args.write_mp3_tag),
                jsonl_path=None if args.jsonl_path is None else Path(str(args.jsonl_path)),
                ffmpeg_exe=None if args.ffmpeg_exe is None else str(args.ffmpeg_exe),
            ),
            metadata=metadata,
        )
        print(f"Saved: {final_audio}")
        if final_metadata.get("metadata_json"):
            print(f"Metadata JSON: {final_metadata['metadata_json']}")
        if final_metadata.get("metadata_jsonl"):
            print(f"Metadata JSONL: {final_metadata['metadata_jsonl']}")
        if args.show_timings:
            print("[timing] ---- long generation chunks ----")
            for index, stage_timings, total_to_decode in timing_logs:
                print(f"[timing] chunk[{index}] ----")
                _print_timings(stage_timings, total_to_decode)
        return

    result = synthesize_text(text_value, None if args.seed is None else int(args.seed))

    print(f"[seed] used_seed: {result.used_seed}")
    if int(args.num_candidates) == 1:
        out_path = save_wav(args.output_wav, result.audio, result.sample_rate)
        print(f"Saved: {out_path}")
    else:
        base_path = Path(str(args.output_wav))
        suffix = base_path.suffix if base_path.suffix else ".wav"
        for i, audio in enumerate(result.audios, start=1):
            out_path = base_path.with_name(f"{base_path.stem}_{i:03d}{suffix}")
            saved = save_wav(out_path, audio, result.sample_rate)
            print(f"Saved[{i}]: {saved}")
    if args.show_timings:
        _print_timings(result.stage_timings, result.total_to_decode)


if __name__ == "__main__":
    main()
